spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 100MB
      max-request-size: 100MB
      file-size-threshold: 0
      resolve-lazily: false

server:
  port: 8848
  tomcat:
    uri-encoding: UTF-8
    max-http-form-post-size: 102400
  max-http-header-size: 102400


